/**
 * Phaserのキーコードをラップ
 */

enum KeyCodes {
  A = Phaser.Input.Keyboard.KeyCodes.A,
  B = Phaser.Input.Keyboard.KeyCodes.B,
  C = Phaser.Input.Keyboard.KeyCodes.C,
  D = Phaser.Input.Keyboard.KeyCodes.D,
  E = Phaser.Input.Keyboard.KeyCodes.E,
  F = Phaser.Input.Keyboard.KeyCodes.F,
  G = Phaser.Input.Keyboard.KeyCodes.G,
  H = Phaser.Input.Keyboard.KeyCodes.H,
  I = Phaser.Input.Keyboard.KeyCodes.I,
  J = Phaser.Input.Keyboard.KeyCodes.J,
  K = Phaser.Input.Keyboard.KeyCodes.K,
  L = Phaser.Input.Keyboard.KeyCodes.L,
  N = Phaser.Input.Keyboard.KeyCodes.N,
  M = Phaser.Input.Keyboard.KeyCodes.M,
  O = Phaser.Input.Keyboard.KeyCodes.O,
  P = Phaser.Input.Keyboard.KeyCodes.P,
  Q = Phaser.Input.Keyboard.KeyCodes.Q,
  R = Phaser.Input.Keyboard.KeyCodes.R,
  S = Phaser.Input.Keyboard.KeyCodes.S,
  T = Phaser.Input.Keyboard.KeyCodes.T,
  U = Phaser.Input.Keyboard.KeyCodes.U,
  V = Phaser.Input.Keyboard.KeyCodes.V,
  W = Phaser.Input.Keyboard.KeyCodes.W,
  X = Phaser.Input.Keyboard.KeyCodes.X,
  Y = Phaser.Input.Keyboard.KeyCodes.Y,
  Z = Phaser.Input.Keyboard.KeyCodes.Z,
  SPACE = Phaser.Input.Keyboard.KeyCodes.SPACE,
  ENTER = Phaser.Input.Keyboard.KeyCodes.ENTER,
  ESC = Phaser.Input.Keyboard.KeyCodes.ESC,
  CTRL = Phaser.Input.Keyboard.KeyCodes.CTRL,
  SHIFT = Phaser.Input.Keyboard.KeyCodes.SHIFT,
  ALT = Phaser.Input.Keyboard.KeyCodes.ALT,
  BACKSPACE = Phaser.Input.Keyboard.KeyCodes.BACKSPACE,
  DEL = Phaser.Input.Keyboard.KeyCodes.DELETE,
  UP = Phaser.Input.Keyboard.KeyCodes.UP,
  DOWN = Phaser.Input.Keyboard.KeyCodes.DOWN,
  LEFT = Phaser.Input.Keyboard.KeyCodes.LEFT,
  RIGHT = Phaser.Input.Keyboard.KeyCodes.RIGHT,
  ONE = Phaser.Input.Keyboard.KeyCodes.ONE,
  TWO = Phaser.Input.Keyboard.KeyCodes.TWO,
  THREE = Phaser.Input.Keyboard.KeyCodes.THREE,
  FOUR = Phaser.Input.Keyboard.KeyCodes.FOUR,
  FIVE = Phaser.Input.Keyboard.KeyCodes.FIVE,
  SIX = Phaser.Input.Keyboard.KeyCodes.SIX,
  SEVEN = Phaser.Input.Keyboard.KeyCodes.SEVEN,
  EIGHT = Phaser.Input.Keyboard.KeyCodes.EIGHT,
  NINE = Phaser.Input.Keyboard.KeyCodes.NINE,
  ZERO = Phaser.Input.Keyboard.KeyCodes.ZERO
}

export default KeyCodes
